### ISSUE TITLE
Compatibility with @capacitor-firebase/messaging

### ISSUE THREAD

**Issue by AntoineAwaida** [Cap-go/capacitor-social-login#31]
I use in the same time https://github.com/capawesome-team/capacitor-firebase, but it seems I'm unable to get a version compatible with this package (since your package is brand new): 

```CocoaPods could not find compatible versions for pod "GoogleUtilities/UserDefaults":
  In Podfile:
    CapacitorFirebaseMessaging (from ../../node_modules/@capacitor-firebase/messaging) was resolved to 6.1.0, which depends on
      FirebaseMessaging (~> 10.25) was resolved to 10.29.0, which depends on
        GoogleUtilities/UserDefaults (~> 7.8)
CapgoCapacitorSocialLogin (from ../../node_modules/@capgo/capacitor-social-login) was resolved to 0.0.42, which depends on
      GoogleSignIn (~> 8.0.0) was resolved to 8.0.0, which depends on
        AppCheckCore (~> 11.0) was resolved to 11.1.0, which depends on
          GoogleUtilities/UserDefaults (~> 8.0)```

**Comment by WcaleNieWolny** [comment]
![image](https://github.com/user-attachments/assets/66b0e937-668a-480c-9d2f-3dbc62616d63)
![image](https://github.com/user-attachments/assets/5c6815bf-baf5-4496-a2a2-9c2313a91de4)

`FirebaseMessaging` version 11.3 uses the newer version of `GoogleUtilities/UserDefaults`. Raise an issue at https://github.com/capawesome-team/capacitor-firebase so that they can update to the latest version of `FirebaseMessaging`.

Also make sure that you are using the latest version of `CapacitorFirebaseMessaging` in your app, because from what I can see, the latest version of `CapacitorFirebaseMessaging` uses `FirebaseMessaging` version 11.0 while your error shows a `FirebaseMessaging` version `10.29.0`.
